#!/usr/bin/env python
import os, sys, urllib2
try:
    import xml.etree.cElementTree as etree
except ImportError:
    try:
        import xml.etree.ElementTree as etree
    except ImportError:
        print 'python >= 2.5'
        sys.exit()

SOLR_URL = os.getenv('SOLR_URL') or 'http://localhost:8080/solr'
SOLR_ADMIN_URL = os.getenv('SOLR_ADMIN_URL') or 'http://localhost:8080/solr/admin/cores'

def get_cores():
    url = '%s?action=status' % SOLR_ADMIN_URL
    f = urllib2.urlopen(url)
    xml = etree.fromstring(f.read())
    cores = [lst.attrib['name'].strip() for lst in xml.findall('./lst/lst')]
    return cores

def main():
    if len(sys.argv) > 1 and 'config' == sys.argv[1]:
        print 'graph_title Requests Per Second'
        print 'graph_category solr'
        print 'graph_vlabel requests / second'
        print 'graph_args --base 1000 -l 0'
        for core in get_cores():
            print 'solr_%s_avgRequestsPerSecond.label %s' % (core, core)
            print 'solr_%s_avgRequestsPerSecond.type GAUGE' % core
            print 'solr_%s_avgRequestsPerSecond.graph yes' % core
        sys.exit()

    for core in get_cores():
        url = '%s/%s/admin/stats.jsp' % (SOLR_URL, core)
        f = urllib2.urlopen(url)
        html = etree.fromstring(f.read())
        for entry in html.findall('./solr-info/QUERYHANDLER/entry'):
            name = entry.find('name').text.strip()
            clazz = entry.find('class').text.strip()
            if (name == 'standard' or name == 'search') and clazz == 'org.apache.solr.handler.component.SearchHandler':
                stats = dict((stat.attrib['name'], stat.text.strip()) for stat in entry.find('stats'))
                print 'solr_%s_avgRequestsPerSecond.value %.5f' % (core, float(stats['avgRequestsPerSecond']))

if '__main__' == __name__:
    main()
